In [ ]:
# %pip install duckdb

Collecting duckdb
  Downloading duckdb-1.5.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (4.2 kB)
Downloading duckdb-1.5.2-cp310-cp310-macosx_11_0_arm64.whl (14.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.2/14.2 MB 21.1 MB/s  0:00:00 eta 0:00:01
Installing collected packages: duckdb
Successfully installed duckdb-1.5.2
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in /opt/anaconda3/envs/eds232-env/lib/python3.10/site-packages (2.1.4)
ERROR: Could not find a version that satisfies the requirement as (from versions: none)
ERROR: No matching distribution found for as
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import duckdb as db

In [ ]:
conn = db.connect(database='database/database.duckdb')

## First method pass the SQL "interactively"

In [5]:
conn.sql("SELECT * FROM Site LIMIT 5")

┌─────────┬─────────────────────┬─────────────────┬──────────┬───────────┬───────┐
│  Code   │      Site_name      │    Location     │ Latitude │ Longitude │ Area  │
│ varchar │       varchar       │     varchar     │  float   │   float   │ float │
├─────────┼─────────────────────┼─────────────────┼──────────┼───────────┼───────┤
│ barr    │ Barrow              │ Alaska, USA     │     71.3 │    -156.6 │ 220.4 │
│ burn    │ Burntpoint Creek    │ Ontario, Canada │     55.2 │     -84.3 │  63.0 │
│ bylo    │ Bylot Island        │ Nunavut, Canada │     73.2 │     -80.0 │ 723.6 │
│ cakr    │ Cape Krusenstern    │ Alaska, USA     │     67.1 │    -163.5 │  54.1 │
│ cari    │ Canning River Delta │ Alaska, USA     │     70.1 │    -145.8 │ 722.0 │
└─────────┴─────────────────────┴─────────────────┴──────────┴───────────┴───────┘

Combine with fetch

In [ ]:
tab = conn.sql("SELECT * FROM Site LIMIT 5").fetchone()
tab

('barr',
 'Barrow',
 'Alaska, USA',
 71.30000305175781,
 -156.60000610351562,
 220.39999389648438)

In [12]:
tab = conn.sql("SELECT * FROM Site LIMIT 5").df()
tab

,Code,Site_name,Location,Latitude,Longitude,Area
0,barr,Barrow,"Alaska, USA",71.300003,-156.600006,220.399994
1,burn,Burntpoint Creek,"Ontario, Canada",55.200001,-84.300003,63.000000
2,bylo,Bylot Island,"Nunavut, Canada",73.199997,-80.000000,723.599976
3,cakr,Cape Krusenstern,"Alaska, USA",67.099998,-163.500000,54.099998
4,cari,Canning River Delta,"Alaska, USA",70.099998,-145.800003,722.000000

## Create Cursor

In [24]:
# create cursor
cur = conn.cursor()
cur.execute("SELECT * FROM site")

# A pointer

In [ ]:
# You can apply the fetchall()..
cur.df()

,Code,Site_name,Location,Latitude,Longitude,Area
0,barr,Barrow,"Alaska, USA",71.300003,-156.600006,220.399994
1,burn,Burntpoint Creek,"Ontario, Canada",55.200001,-84.300003,63.000000
2,bylo,Bylot Island,"Nunavut, Canada",73.199997,-80.000000,723.599976
3,cakr,Cape Krusenstern,"Alaska, USA",67.099998,-163.500000,54.099998
4,cari,Canning River Delta,"Alaska, USA",70.099998,-145.800003,722.000000
5,chau,Chaun River Delta,"Chukotka, Russia",68.800003,170.600006,248.199997
6,chur,Churchill,"Manitoba, Canada",58.700001,-93.800003,866.900024
7,coat,Coats Island,"Nunavut, Canada",62.900002,-82.500000,1239.099976
8,colv,Colville River Delta,"Alaska, USA",70.400002,-150.699997,324.799988
9,eaba,East Bay,"Nunavut, Canada",64.000000,-81.699997,1205.500000
10,iglo,Igloolik,"Nunavut, Canada",69.400002,-81.599998,59.799999
11,ikpi,Ikpikpuk,"Alaska, USA",70.599998,-154.699997,174.100006
12,lkri,Lower Khatanga River,"Krasnoyarsk, Russia",72.900002,106.099998,270.899994
13,made,Mackenzie River Delta,"Northwest Territories, Canada",69.400002,-135.000000,667.299988
14,nome,Nome,"Alaska, USA",64.400002,-164.899994,90.099998
15,prba,Prudhoe Bay,"Alaska, USA",70.300003,-148.600006,120.000000

The cursors dissapears after use! 
Create several in a loop

In [27]:
cur.execute("SELECT * FROM site")
cur.fetchone()[0]

'barr'

In [30]:
# We want to iterate through the rows and pring the site code
cur.execute("SELECT * FROM site")

for row in cur.fetchall():
    print(row[0])

barr
burn
bylo
cakr
cari
chau
chur
coat
colv
eaba
iglo
ikpi
lkri
made
nome
prba

In [32]:
cur.execute("SELECT * FROM site")

while True:
    row = cur.fetchone()
    if row == None:
            break
    print(f"Site code: {row[0]}")

Site code: barr
Site code: burn
Site code: bylo
Site code: cakr
Site code: cari
Site code: chau
Site code: chur
Site code: coat
Site code: colv
Site code: eaba
Site code: iglo
Site code: ikpi
Site code: lkri
Site code: made
Site code: nome
Site code: prba

In [33]:
# You can create table 
cur.execute("""CREATE TEMP TABLE temp_nests 
            AS SELECT * FROM Bird_nests""")
cur.execute("SELECT * FROM temp_nests").fetchall()

[('b14.6',
  2014,
  'chur',
  '14HPE1',
  'sepl',
  'vloverti',
  datetime.date(2014, 6, 14),
  None,
  3,
  None,
  None),
 ('b11.7',
  2011,
  'eaba',
  '11eaba',
  'wrsa',
  'bhill',
  datetime.date(2011, 7, 10),
  'searcher',
  4,
  None,
  None),
 ('b11.6',
  2011,
  'eaba',
  '11eabaagc01',
  'amgp',
  'dkessler',
  datetime.date(2011, 6, 24),
  'searcher',
  4,
  6.0,
  'float'),
 ('b11.6',
  2011,
  'eaba',
  '11eabaagv01',
  'amgp',
  'dkessler',
  datetime.date(2011, 6, 25),
  'searcher',
  3,
  3.0,
  'float'),
 ('b11.6',
  2011,
  'eaba',
  '11eababbc02',
  'bbpl',
  'dkessler',
  datetime.date(2011, 6, 24),
  'searcher',
  4,
  4.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eababsv01',
  'wrsa',
  'bhill',
  datetime.date(2011, 7, 7),
  'searcher',
  4,
  2.0,
  'float'),
 ('b11.6',
  2011,
  'eaba',
  '11eabaduh01',
  'dunl',
  'dkessler',
  datetime.date(2011, 6, 28),
  'searcher',
  3,
  2.0,
  'float'),
 ('b11.6',
  2011,
  'eaba',
  '11eabaduv01',
  'dunl',
  'dkessler',
  datetime.date(2011, 6, 29),
  'searcher',
  4,
  5.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabarpc01',
  'reph',
  'bhill',
  datetime.date(2011, 7, 8),
  'searcher',
  4,
  4.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabarpc02',
  'reph',
  'bhill',
  datetime.date(2011, 7, 8),
  'searcher',
  3,
  4.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabarpc03',
  'reph',
  'bhill',
  datetime.date(2011, 7, 9),
  'searcher',
  4,
  6.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabarph04',
  'reph',
  'rlanctot',
  datetime.date(2011, 7, 4),
  'searcher',
  4,
  5.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabarph05',
  'reph',
  'rlanctot',
  datetime.date(2011, 7, 5),
  'searcher',
  4,
  4.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabarph06',
  'reph',
  'bhill',
  datetime.date(2011, 7, 6),
  'searcher',
  3,
  4.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabarph07',
  'reph',
  'bhill',
  datetime.date(2011, 7, 8),
  'searcher',
  4,
  4.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabarph08',
  'reph',
  'jzamuido',
  datetime.date(2011, 7, 13),
  'searcher',
  4,
  5.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabarpm02',
  'reph',
  'bhill',
  datetime.date(2011, 7, 7),
  'searcher',
  4,
  4.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabarth07',
  'rutu',
  'jzamuido',
  datetime.date(2011, 7, 15),
  'searcher',
  4,
  12.0,
  'float'),
 ('b11.6',
  2011,
  'eaba',
  '11eabartm01',
  'rutu',
  'dkessler',
  datetime.date(2011, 6, 26),
  'searcher',
  4,
  3.0,
  'float'),
 ('b11.6',
  2011,
  'eaba',
  '11eabaspc01',
  'sepl',
  'dkessler',
  datetime.date(2011, 6, 29),
  'searcher',
  4,
  4.0,
  'float'),
 ('b11.6',
  2011,
  'eaba',
  '11eabaspc02',
  'sepl',
  'dkessler',
  datetime.date(2011, 6, 30),
  'searcher',
  4,
  9.0,
  'float'),
 ('b11.6',
  2011,
  'eaba',
  '11eabasph04',
  'sepl',
  'dkessler',
  datetime.date(2011, 6, 29),
  'searcher',
  4,
  7.0,
  'hatch'),
 ('b11.6',
  2011,
  'eaba',
  '11eabasph05',
  'sepl',
  'dkessler',
  datetime.date(2011, 6, 29),
  'searcher',
  4,
  6.0,
  'hatch'),
 ('b11.6',
  2011,
  'eaba',
  '11eabaspm01',
  'sepl',
  'dkessler',
  datetime.date(2011, 6, 26),
  'searcher',
  3,
  0.0,
  'float'),
 ('b11.6',
  2011,
  'eaba',
  '11eabaspm02',
  'sepl',
  'dkessler',
  datetime.date(2011, 6, 26),
  'searcher',
  4,
  8.0,
  'float'),
 ('b11.6',
  2011,
  'eaba',
  '11eabaspm03',
  'sepl',
  'dkessler',
  datetime.date(2011, 6, 30),
  'searcher',
  4,
  2.0,
  'float'),
 ('b11.6',
  2011,
  'eaba',
  '11eabaspv01',
  'sepl',
  'dkessler',
  datetime.date(2011, 6, 28),
  'searcher',
  4,
  9.0,
  'hatch'),
 ('b11.6',
  2011,
  'eaba',
  '11eabawrc01',
  'wrsa',
  'dkessler',
  datetime.date(2011, 6, 24),
  'searcher',
  4,
  4.0,
  'hatch'),
 ('b11.7',
  2011,
  'eaba',
  '11eabawrc03',
  'wrsa',
  'jzamuido',
  datetime.date(2011, 7, 13),
  'searcher',
  4,
  2.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabawrc04',
  'wrsa',
  'jzamuido',
  datetime.date(2011, 7, 13),
  'searcher',
  3,
  2.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabawrc05',
  'wrsa',
  'jzamuido',
  datetime.date(2011, 7, 13),
  'searcher',
  4,
  11.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabawrc06',
  'wrsa',
  'jzamuido',
  datetime.date(2011, 7, 19),
  'searcher',
  4,
  2.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabawrc07',
  'wrsa',
  'jzamuido',
  datetime.date(2011, 7, 19),
  'searcher',
  3,
  11.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabawrh02',
  'wrsa',
  'rlanctot',
  datetime.date(2011, 7, 5),
  'searcher',
  4,
  3.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabawrh03',
  'wrsa',
  'rlanctot',
  datetime.date(2011, 7, 5),
  'searcher',
  3,
  3.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabawrh04',
  'wrsa',
  'bhill',
  datetime.date(2011, 7, 6),
  'searcher',
  4,
  3.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabawrh05',
  'wrsa',
  'jzamuido',
  datetime.date(2011, 7, 16),
  'searcher',
  3,
  3.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabawrh06',
  'wrsa',
  'jzamuido',
  datetime.date(2011, 7, 19),
  'searcher',
  4,
  3.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabawrh07',
  'wrsa',
  'jzamuido',
  datetime.date(2011, 7, 19),
  'searcher',
  4,
  12.0,
  'float'),
 ('b11.6',
  2011,
  'eaba',
  '11eabawrm01',
  'wrsa',
  'abankert',
  datetime.date(2011, 6, 20),
  'searcher',
  4,
  3.0,
  'float'),
 ('b11.7',
  2011,
  'eaba',
  '11eabawrm04',
  'wrsa',
  'ssaalfeld',
  datetime.date(2011, 7, 2),
  'searcher',
  4,
  5.0,
  'hatch'),
 ('b11.7',
  2011,
  'eaba',
  '11eabawrm06',
  'wrsa',
  'bhill',
  datetime.date(2011, 7, 10),
  'searcher',
  3,
  0.0,
  'float'),
 ('b13.6',
  2013,
  'eaba',
  '13eababba01',
  'bbpl',
  'amould',
  datetime.date(2013, 6, 25),
  'searcher',
  4,
  3.0,
  'float'),
 ('b13.6',
  2013,
  'eaba',
  '13eababba04',
  'bbpl',
  'amould',
  datetime.date(2013, 6, 27),
  'searcher',
  4,
  3.0,
  'float'),
 ('b13.6',
  2013,
  'eaba',
  '13eababbs01',
  'bbpl',
  'amould',
  datetime.date(2013, 6, 24),
  'searcher',
  2,
  None,
  None),
 ('b13.7',
  2013,
  'eaba',
  '13eabadue01',
  'dunl',
  'amould',
  datetime.date(2013, 7, 1),
  'searcher',
  2,
  None,
  None),
 ('b13.6',
  2013,
  'eaba',
  '13eabarpa01',
  'reph',
  'amould',
  datetime.date(2013, 6, 27),
  'searcher',
  4,
  2.0,
  'float'),
 ('b13.7',
  2013,
  'eaba',
  '13eabarpa05',
  'reph',
  'amould',
  datetime.date(2013, 7, 2),
  'searcher',
  1,
  None,
  None),
 ('b13.7',
  2013,
  'eaba',
  '13eabarpe04',
  'reph',
  'rlanctot',
  datetime.date(2013, 7, 4),
  'searcher',
  3,
  None,
  None),
 ('b13.7',
  2013,
  'eaba',
  '13eabarpl01',
  'reph',
  'amould',
  datetime.date(2013, 7, 2),
  'searcher',
  3,
  None,
  None),
 ('b13.7',
  2013,
  'eaba',
  '13eabarps03',
  'reph',
  'rlanctot',
  datetime.date(2013, 7, 4),
  'searcher',
  4,
  5.0,
  'float'),
 ('b13.7',
  2013,
  'eaba',
  '13eabarps05',
  'reph',
  'wenglish',
  datetime.date(2013, 7, 12),
  'searcher',
  4,
  1.0,
  'float'),
 ('b13.7',
  2013,
  'eaba',
  '13eabarue01',
  'rutu',
  'amould',
  datetime.date(2013, 7, 3),
  'searcher',
  4,
  11.0,
  'float'),
 ('b13.7',
  2013,
  'eaba',
  '13eabarus03',
  'rutu',
  'wenglish',
  datetime.date(2013, 7, 9),
  'searcher',
  4,
  4.0,
  'float'),
 ('b13.7',
  2013,
  'eaba',
  '13eabasee01',
  'sesa',
  'amould',
  datetime.date(2013, 7, 1),
  'searcher',
  4,
  None,
  'float'),
 ('b13.7',
  2013,
  'eaba',
  '13eabasee02',
  'sesa',
  'amould',
  datetime.date(2013, 7, 2),
  'searcher',
  4,
  8.0,
  'float'),
 ('b13.6',
  2013,
  'eaba',
  '13eabaspl01',
  'sepl',
  'amould',
  datetime.date(2013, 6, 25),
  'searcher',
  4,
  4.0,
  'hatch'),
 ('b13.6',
  2013,
  'eaba',
  '13eabaspl02',
  'sepl',
  'amould',
  datetime.date(2013, 6, 27),
  'searcher',
  4,
  10.0,
  'hatch'),
 ('b13.6',
  2013,
  'eaba',
  '13eabawra02',
  'wrsa',
  'amould',
  datetime.date(2013, 6, 25),
  'searcher',
  4,
  7.0,
  'hatch'),
 ('b13.6',
  2013,
  'eaba',
  '13eabawra03',
  'wrsa',
  'amould',
  datetime.date(2013, 6, 25),
  'searcher',
  4,
  6.0,
  'float'),
 ('b13.7',
  2013,
  'eaba',
  '13eabawra04',
  'wrsa',
  'amould',
  datetime.date(2013, 7, 2),
  'searcher',
  1,
  None,
  'lay'),
 ('b13.7',
  2013,
  'eaba',
  '13eabawra05',
  'wrsa',
  'wenglish',
  datetime.date(2013, 7, 7),
  'searcher',
  4,
  4.0,
  'float'),
 ('b13.7',
  2013,
  'eaba',
  '13eabawra06',
  'wrsa',
  'wenglish',
  datetime.date(2013, 7, 8),
  'searcher',
  4,
  10.0,
  'float'),
 ('b13.7',
  2013,
  'eaba',
  '13eabawra07',
  'wrsa',
  'wenglish',
  datetime.date(2013, 7, 11),
  'searcher',
  3,
  4.0,
  'float'),
 ('b13.7',
  2013,
  'eaba',
  '13eabawra08',
  'wrsa',
  'wenglish',
  datetime.date(2013, 7, 12),
  'searcher',
  2,
  None,
  None),
 ('b13.7',
  2013,
  'eaba',
  '13eabawre01',
  'wrsa',
  'amould',
  datetime.date(2013, 7, 1),
  'searcher',
  4,
  None,
  'float'),
 ('b13.7',
  2013,
  'eaba',
  '13eabawre02',
  'wrsa',
  'amould',
  datetime.date(2013, 7, 1),
  'searcher',
  4,
  None,
  None),
 ('b13.7',
  2013,
  'eaba',
  '13eabawre03',
  'wrsa',
  'rlanctot',
  datetime.date(2013, 7, 4),
  'searcher',
  4,
  10.0,
  'hatch'),
 ('b13.7',
  2013,
  'eaba',
  '13eabawre04',
  'wrsa',
  'wenglish',
  datetime.date(2013, 7, 10),
  'searcher',
  4,
  None,
  None),
 ('b13.7',
  2013,
  'eaba',
  '13eabawre05',
  'wrsa',
  'wenglish',
  datetime.date(2013, 7, 10),
  'searcher',
  3,
  None,
  None),
 ('b13.6',
  2013,
  'eaba',
  '13eabawrl01',
  'wrsa',
  'dkessler',
  datetime.date(2013, 6, 21),
  'searcher',
  4,
  None,
  'hatch'),
 ('b13.6',
  2013,
  'eaba',
  '13eabawrl02',
  'wrsa',
  'amould',
  datetime.date(2013, 6, 27),
  'searcher',
  4,
  3.0,
  'hatch'),
 ('b13.7',
  2013,
  'eaba',
  '13eabawrl03',
  'wrsa',
  'rlanctot',
  datetime.date(2013, 7, 4),
  'searcher',
  4,
  4.0,
  'float'),
 ('b13.7',
  2013,
  'eaba',
  '13eabawrl04',
  'wrsa',
  'wenglish',
  datetime.date(2013, 7, 6),
  'searcher',
  4,
  12.0,
  'float'),
 ('b13.7',
  2013,
  'eaba',
  '13eabawrl05',
  'wrsa',
  'bkaselow',
  datetime.date(2013, 7, 18),
  'searcher',
  4,
  10.0,
  'float'),
 ('b13.7',
  2013,
  'eaba',
  '13eabawrl06',
  'wrsa',
  'bkaselow',
  datetime.date(2013, 7, 19),
  'searcher',
  3,
  10.0,
  'float'),
 ('b13.6',
  2013,
  'eaba',
  '13eabawrs01',
  'wrsa',
  'dkessler',
  datetime.date(2013, 6, 21),
  'searcher',
  3,
  None,
  'lay'),
 ('b13.6',
  2013,
  'eaba',
  '13eabawrs02',
  'wrsa',
  'amould',
  datetime.date(2013, 6, 28),
  'searcher',
  5,
  3.0,
  'hatch'),
 ('b13.7',
  2013,
  'eaba',
  '13eabawrs03',
  'wrsa',
  'amould',
  datetime.date(2013, 7, 1),
  'searcher',
  4,
  10.0,
  'hatch'),
 ('b13.7',
  2013,
  'eaba',
  '13eabawrs04',
  'wrsa',
  'amould',
  datetime.date(2013, 7, 2),
  'searcher',
  4,
  10.0,
  'hatch'),
 ('b13.7',
  2013,
  'eaba',
  '13eabawrs05',
  'wrsa',
  'wenglish',
  datetime.date(2013, 7, 8),
  'searcher',
  4,
  14.0,
  'hatch'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs001',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 11),
  'rope',
  3,
  None,
  'lay'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs002',
  'dunl',
  'bhill',
  datetime.date(2010, 6, 11),
  'bander',
  2,
  None,
  'lay'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs004',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 14),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs007',
  'reph',
  'bhill',
  datetime.date(2010, 6, 14),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs015',
  'dunl',
  'lworing',
  datetime.date(2010, 6, 18),
  'bander',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs020',
  'reph',
  'bhill',
  datetime.date(2010, 6, 15),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs022',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 15),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs023',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 15),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs024',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 15),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs025',
  'dunl',
  'bhill',
  datetime.date(2010, 6, 15),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs026',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 15),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs027',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 16),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs028',
  'bbpl',
  'bhill',
  datetime.date(2010, 6, 16),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs029',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 16),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs030',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 16),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs031',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 16),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs032',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 16),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs035',
  'btgo',
  'bhill',
  datetime.date(2010, 6, 16),
  'rope',
  None,
  None,
  None),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs036',
  'dunl',
  'bhill',
  datetime.date(2010, 6, 16),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs037',
  'pesa',
  'lworing',
  datetime.date(2010, 6, 22),
  'rope',
  4,
  None,
  None),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs038',
  'pesa',
  'lworing',
  datetime.date(2010, 6, 25),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs039',
  'pesa',
  'lworing',
  datetime.date(2010, 6, 25),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs040',
  'lbdo',
  'lworing',
  datetime.date(2010, 6, 25),
  'rope',
  2,
  None,
  'lay'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs041',
  'sesa',
  'rlanctot',
  datetime.date(2010, 6, 26),
  'bander',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs042',
  'sesa',
  'rlanctot',
  datetime.date(2010, 6, 26),
  'bander',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs044',
  'pesa',
  'rlanctot',
  datetime.date(2010, 6, 27),
  'bander',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cjs047',
  'pesa',
  'mbwunder',
  datetime.date(2010, 6, 28),
  'bander',
  4,
  None,
  None),
 ('b10.7',
  2010,
  'ikpi',
  '10ikpi10cjs051',
  'rnph',
  'rlanctot',
  datetime.date(2010, 7, 3),
  'bander',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cmb007',
  'dunl',
  'bhill',
  datetime.date(2010, 6, 12),
  'bander',
  3,
  None,
  'lay'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cmb011',
  'pesa',
  'lworing',
  datetime.date(2010, 6, 19),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cmb015',
  'pesa',
  'mbwunder',
  datetime.date(2010, 6, 30),
  'rope',
  None,
  None,
  None),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cmb017',
  'pesa',
  'mbwunder',
  datetime.date(2010, 6, 30),
  None,
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10cmb018',
  'btgo',
  'mbwunder',
  datetime.date(2010, 6, 30),
  'bander',
  None,
  None,
  None),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj012',
  'rnph',
  'bhill',
  datetime.date(2010, 6, 12),
  None,
  1,
  None,
  'lay'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj013',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 12),
  None,
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj014',
  'dunl',
  'bhill',
  datetime.date(2010, 6, 12),
  'rope',
  1,
  None,
  'lay'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj015',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 12),
  'rope',
  3,
  None,
  'lay'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj016',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 12),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj017',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 12),
  None,
  3,
  None,
  'lay'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj018',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 13),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj019',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 13),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj021',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 13),
  'rope',
  3,
  None,
  'lay'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj023',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 13),
  'rope',
  3,
  None,
  'lay'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj024',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 13),
  'rope',
  3,
  None,
  'lay'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj025',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 13),
  'bander',
  3,
  None,
  'lay'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj026',
  'reph',
  'bhill',
  datetime.date(2010, 6, 13),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj027',
  'dunl',
  'bhill',
  datetime.date(2010, 6, 13),
  'rope',
  3,
  None,
  'lay'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj028',
  'dunl',
  'bhill',
  datetime.date(2010, 6, 13),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj031',
  'sesa',
  'bhill',
  datetime.date(2010, 6, 13),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj054',
  'sesa',
  'lworing',
  datetime.date(2010, 6, 19),
  None,
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj056',
  'pesa',
  'lworing',
  datetime.date(2010, 6, 19),
  'bander',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj060',
  'sesa',
  'lworing',
  datetime.date(2010, 6, 20),
  'bander',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj064',
  'sesa',
  'lworing',
  datetime.date(2010, 6, 20),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj078',
  'dunl',
  'lworing',
  datetime.date(2010, 6, 23),
  'rope',
  3,
  None,
  None),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj083',
  'dunl',
  'lworing',
  datetime.date(2010, 6, 24),
  'rope',
  4,
  None,
  'float'),
 ('b10.6',
  2010,
  'ikpi',
  '10ikpi10vj090',
  'rnph',
  'lworing',
  datetime.date(2010, 6, 25),
  'bander',
  3,
  None,
  None),
 ('b10.7',
  2010,
  'ikpi',
  '10ikpi10vj094',
  'sesa',
  'rlanctot',
  datetime.date(2010, 7, 2),
  'bander',
  None,
  None,
  None),
 ('b11.7',
  2011,
  'eaba',
  '11eabarph03',
  'reph',
  'dkessler',
  datetime.date(2011, 7, 1),
  'searcher',
  4,
  4.0,
  'float'),
 ('b11.6',
  2011,
  'eaba',
  '11eabasph01',
  'sepl',
  'abankert',
  datetime.date(2011, 6, 22),
  'searcher',
  4,
  3.0,
  'hatch'),
 ('b11.6',
  2011,
  'eaba',
  '11eabasph03',
  'sepl',
  'abankert',
  datetime.date(2011, 6, 23),
  'searcher',
  4,
  4.0,
  'float'),
 ('b11.6',
  2011,
  'eaba',
  '11eabawrh01',
  'wrsa',
  'dkessler',
  datetime.date(2011, 6, 28),
  'searcher',
  4,
  4.0,
  'float'),
 ('b11.6',
  2011,
  'eaba',
  '11eabawrm02',
  'wrsa',
  'abankert',
  datetime.date(2011, 6, 20),
  'searcher',
  4,
  0.0,
  'lay'),
 ('b11.6',
  2011,
  'eaba',
  '11eabawrm03',
  'wrsa',
  'abankert',
  datetime.date(2011, 6, 21),
  'searcher',
  3,
  None,
  None),
 ('b11.6',
  2011,
  'eaba',
  '11eabawrv01',
  'wrsa',
  'abankert',
  datetime.date(2011, 6, 22),
  'searcher',
  4,
  3.0,
  'float'),
 ('b13.6',
  2013,
  'eaba',
  '13eabaspp02',
  'sepl',
  'amould',
  datetime.date(2013, 6, 27),
  'searcher',
  4,
  None,
  'lay'),
 ('b11.7',
  2011,
  'eaba',
  '11eabarph02',
  'reph',
  'dkessler',
  datetime.date(2011, 7, 1),
  'searcher',
  4,
  None,
  None),
 ('b11.7',

In [34]:
# Close connection
conn.close()